### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by aishcann** [EvanChenoweth/tic-tac-toe-game#1]
Hi Ervin!

Currently your tic-tac-toe is missing a few requirements, including draw detection and not stopping the game when win-lose-draw is detected. Take a look at the requirements again, check your work, and make the necessary corrections. Reference the class' tic-tac-toe review and/or attend office hours to get support.

**Comment by EvanChenoweth** [comment]
Ok, changes have been made to include a function that checks for tie games and no moves are allowed to be made after a player has won or a game has been tied.
